// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("API.Data.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Latest model with high-resolution display.",
                            ImageUrl = "https://example.com/images/smartphone.jpg",
                            Name = "Smartphone",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Portable speaker with deep bass.",
                            ImageUrl = "https://example.com/images/speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "27-inch 144Hz gaming monitor.",
                            ImageUrl = "https://example.com/images/monitor.jpg",
                            Name = "Gaming Monitor",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Multiport adapter for laptops.",
                            ImageUrl = "https://example.com/images/hub.jpg",
                            Name = "USB-C Hub",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Over-ear headphones with active noise cancellation.",
                            ImageUrl = "https://example.com/images/headphones.jpg",
                            Name = "Noise Cancelling Headphones",
                            Price = 199.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
